(cl:defpackage jsk_rviz_plugins-msg
  (:use )
  (:export
   "<OBJECTFITCOMMAND>"
   "OBJECTFITCOMMAND"
   "<OVERLAYMENU>"
   "OVERLAYMENU"
   "<OVERLAYTEXT>"
   "OVERLAYTEXT"
   "<PICTOGRAM>"
   "PICTOGRAM"
   "<PICTOGRAMARRAY>"
   "PICTOGRAMARRAY"
   "<RECORDCOMMAND>"
   "RECORDCOMMAND"
   "<STRINGSTAMPED>"
   "STRINGSTAMPED"
   "<TRANSFORMABLEMARKEROPERATE>"
   "TRANSFORMABLEMARKEROPERATE"
  ))

