// Generated by gencpp from file jsk_recognition_msgs/Accuracy.msg
// DO NOT EDIT!


#ifndef JSK_RECOGNITION_MSGS_MESSAGE_ACCURACY_H
#define JSK_RECOGNITION_MSGS_MESSAGE_ACCURACY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace jsk_recognition_msgs
{
template <class ContainerAllocator>
struct Accuracy_
{
  typedef Accuracy_<ContainerAllocator> Type;

  Accuracy_()
    : header()
    , accuracy(0.0)  {
    }
  Accuracy_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , accuracy(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _accuracy_type;
  _accuracy_type accuracy;





  typedef boost::shared_ptr< ::jsk_recognition_msgs::Accuracy_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jsk_recognition_msgs::Accuracy_<ContainerAllocator> const> ConstPtr;

}; // struct Accuracy_

typedef ::jsk_recognition_msgs::Accuracy_<std::allocator<void> > Accuracy;

typedef boost::shared_ptr< ::jsk_recognition_msgs::Accuracy > AccuracyPtr;
typedef boost::shared_ptr< ::jsk_recognition_msgs::Accuracy const> AccuracyConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jsk_recognition_msgs::Accuracy_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jsk_recognition_msgs::Accuracy_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::jsk_recognition_msgs::Accuracy_<ContainerAllocator1> & lhs, const ::jsk_recognition_msgs::Accuracy_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.accuracy == rhs.accuracy;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::jsk_recognition_msgs::Accuracy_<ContainerAllocator1> & lhs, const ::jsk_recognition_msgs::Accuracy_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace jsk_recognition_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::jsk_recognition_msgs::Accuracy_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jsk_recognition_msgs::Accuracy_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jsk_recognition_msgs::Accuracy_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jsk_recognition_msgs::Accuracy_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jsk_recognition_msgs::Accuracy_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jsk_recognition_msgs::Accuracy_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jsk_recognition_msgs::Accuracy_<ContainerAllocator> >
{
  static const char* value()
  {
    return "198da9dc2684aac2aa03a85a3344f5ef";
  }

  static const char* value(const ::jsk_recognition_msgs::Accuracy_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x198da9dc2684aac2ULL;
  static const uint64_t static_value2 = 0xaa03a85a3344f5efULL;
};

template<class ContainerAllocator>
struct DataType< ::jsk_recognition_msgs::Accuracy_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jsk_recognition_msgs/Accuracy";
  }

  static const char* value(const ::jsk_recognition_msgs::Accuracy_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jsk_recognition_msgs::Accuracy_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float32 accuracy\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::jsk_recognition_msgs::Accuracy_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jsk_recognition_msgs::Accuracy_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.accuracy);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Accuracy_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jsk_recognition_msgs::Accuracy_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jsk_recognition_msgs::Accuracy_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "accuracy: ";
    Printer<float>::stream(s, indent + "  ", v.accuracy);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JSK_RECOGNITION_MSGS_MESSAGE_ACCURACY_H
