// Generated by gencpp from file jsk_recognition_msgs/SaveMeshRequest.msg
// DO NOT EDIT!


#ifndef JSK_RECOGNITION_MSGS_MESSAGE_SAVEMESHREQUEST_H
#define JSK_RECOGNITION_MSGS_MESSAGE_SAVEMESHREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <jsk_recognition_msgs/BoundingBox.h>

namespace jsk_recognition_msgs
{
template <class ContainerAllocator>
struct SaveMeshRequest_
{
  typedef SaveMeshRequest_<ContainerAllocator> Type;

  SaveMeshRequest_()
    : ground_frame_id()
    , box()  {
    }
  SaveMeshRequest_(const ContainerAllocator& _alloc)
    : ground_frame_id(_alloc)
    , box(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _ground_frame_id_type;
  _ground_frame_id_type ground_frame_id;

   typedef  ::jsk_recognition_msgs::BoundingBox_<ContainerAllocator>  _box_type;
  _box_type box;





  typedef boost::shared_ptr< ::jsk_recognition_msgs::SaveMeshRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jsk_recognition_msgs::SaveMeshRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SaveMeshRequest_

typedef ::jsk_recognition_msgs::SaveMeshRequest_<std::allocator<void> > SaveMeshRequest;

typedef boost::shared_ptr< ::jsk_recognition_msgs::SaveMeshRequest > SaveMeshRequestPtr;
typedef boost::shared_ptr< ::jsk_recognition_msgs::SaveMeshRequest const> SaveMeshRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jsk_recognition_msgs::SaveMeshRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jsk_recognition_msgs::SaveMeshRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::jsk_recognition_msgs::SaveMeshRequest_<ContainerAllocator1> & lhs, const ::jsk_recognition_msgs::SaveMeshRequest_<ContainerAllocator2> & rhs)
{
  return lhs.ground_frame_id == rhs.ground_frame_id &&
    lhs.box == rhs.box;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::jsk_recognition_msgs::SaveMeshRequest_<ContainerAllocator1> & lhs, const ::jsk_recognition_msgs::SaveMeshRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace jsk_recognition_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::jsk_recognition_msgs::SaveMeshRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jsk_recognition_msgs::SaveMeshRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jsk_recognition_msgs::SaveMeshRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jsk_recognition_msgs::SaveMeshRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jsk_recognition_msgs::SaveMeshRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jsk_recognition_msgs::SaveMeshRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jsk_recognition_msgs::SaveMeshRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aedbb75b25dc1f22d6170286e35b1132";
  }

  static const char* value(const ::jsk_recognition_msgs::SaveMeshRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaedbb75b25dc1f22ULL;
  static const uint64_t static_value2 = 0xd6170286e35b1132ULL;
};

template<class ContainerAllocator>
struct DataType< ::jsk_recognition_msgs::SaveMeshRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jsk_recognition_msgs/SaveMeshRequest";
  }

  static const char* value(const ::jsk_recognition_msgs::SaveMeshRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jsk_recognition_msgs::SaveMeshRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string ground_frame_id  # to create solid model\n"
"jsk_recognition_msgs/BoundingBox box  # to crop mesh\n"
"\n"
"================================================================================\n"
"MSG: jsk_recognition_msgs/BoundingBox\n"
"# BoundingBox represents a oriented bounding box.\n"
"Header header\n"
"geometry_msgs/Pose pose\n"
"geometry_msgs/Vector3 dimensions  # size of bounding box (x, y, z)\n"
"# You can use this field to hold value such as likelihood\n"
"float32 value\n"
"uint32 label\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::jsk_recognition_msgs::SaveMeshRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jsk_recognition_msgs::SaveMeshRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ground_frame_id);
      stream.next(m.box);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SaveMeshRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jsk_recognition_msgs::SaveMeshRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jsk_recognition_msgs::SaveMeshRequest_<ContainerAllocator>& v)
  {
    s << indent << "ground_frame_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.ground_frame_id);
    s << indent << "box: ";
    s << std::endl;
    Printer< ::jsk_recognition_msgs::BoundingBox_<ContainerAllocator> >::stream(s, indent + "  ", v.box);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JSK_RECOGNITION_MSGS_MESSAGE_SAVEMESHREQUEST_H
