// Generated by gencpp from file jsk_recognition_msgs/TimeRange.msg
// DO NOT EDIT!


#ifndef JSK_RECOGNITION_MSGS_MESSAGE_TIMERANGE_H
#define JSK_RECOGNITION_MSGS_MESSAGE_TIMERANGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace jsk_recognition_msgs
{
template <class ContainerAllocator>
struct TimeRange_
{
  typedef TimeRange_<ContainerAllocator> Type;

  TimeRange_()
    : header()
    , start()
    , end()  {
    }
  TimeRange_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , start()
    , end()  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef ros::Time _start_type;
  _start_type start;

   typedef ros::Time _end_type;
  _end_type end;





  typedef boost::shared_ptr< ::jsk_recognition_msgs::TimeRange_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jsk_recognition_msgs::TimeRange_<ContainerAllocator> const> ConstPtr;

}; // struct TimeRange_

typedef ::jsk_recognition_msgs::TimeRange_<std::allocator<void> > TimeRange;

typedef boost::shared_ptr< ::jsk_recognition_msgs::TimeRange > TimeRangePtr;
typedef boost::shared_ptr< ::jsk_recognition_msgs::TimeRange const> TimeRangeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jsk_recognition_msgs::TimeRange_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jsk_recognition_msgs::TimeRange_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::jsk_recognition_msgs::TimeRange_<ContainerAllocator1> & lhs, const ::jsk_recognition_msgs::TimeRange_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.start == rhs.start &&
    lhs.end == rhs.end;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::jsk_recognition_msgs::TimeRange_<ContainerAllocator1> & lhs, const ::jsk_recognition_msgs::TimeRange_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace jsk_recognition_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::jsk_recognition_msgs::TimeRange_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jsk_recognition_msgs::TimeRange_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jsk_recognition_msgs::TimeRange_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jsk_recognition_msgs::TimeRange_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jsk_recognition_msgs::TimeRange_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jsk_recognition_msgs::TimeRange_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jsk_recognition_msgs::TimeRange_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a8a69e1e51e3731790c8e4120a725398";
  }

  static const char* value(const ::jsk_recognition_msgs::TimeRange_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa8a69e1e51e37317ULL;
  static const uint64_t static_value2 = 0x90c8e4120a725398ULL;
};

template<class ContainerAllocator>
struct DataType< ::jsk_recognition_msgs::TimeRange_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jsk_recognition_msgs/TimeRange";
  }

  static const char* value(const ::jsk_recognition_msgs::TimeRange_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jsk_recognition_msgs::TimeRange_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Represents range of time.\n"
"std_msgs/Header header\n"
"time start\n"
"time end\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::jsk_recognition_msgs::TimeRange_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jsk_recognition_msgs::TimeRange_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.start);
      stream.next(m.end);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TimeRange_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jsk_recognition_msgs::TimeRange_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jsk_recognition_msgs::TimeRange_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "start: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.start);
    s << indent << "end: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.end);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JSK_RECOGNITION_MSGS_MESSAGE_TIMERANGE_H
