# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from jsk_recognition_msgs/BoundingBoxMovement.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import jsk_recognition_msgs.msg
import std_msgs.msg

class BoundingBoxMovement(genpy.Message):
  _md5sum = "60aeb288c030d1b8a67ddeedc91812f0"
  _type = "jsk_recognition_msgs/BoundingBoxMovement"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header header
BoundingBox box
geometry_msgs/Pose handle_pose
geometry_msgs/PoseStamped destination

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: jsk_recognition_msgs/BoundingBox
# BoundingBox represents a oriented bounding box.
Header header
geometry_msgs/Pose pose
geometry_msgs/Vector3 dimensions  # size of bounding box (x, y, z)
# You can use this field to hold value such as likelihood
float32 value
uint32 label

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z
================================================================================
MSG: geometry_msgs/PoseStamped
# A Pose with reference coordinate frame and timestamp
Header header
Pose pose
"""
  __slots__ = ['header','box','handle_pose','destination']
  _slot_types = ['std_msgs/Header','jsk_recognition_msgs/BoundingBox','geometry_msgs/Pose','geometry_msgs/PoseStamped']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,box,handle_pose,destination

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(BoundingBoxMovement, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.box is None:
        self.box = jsk_recognition_msgs.msg.BoundingBox()
      if self.handle_pose is None:
        self.handle_pose = geometry_msgs.msg.Pose()
      if self.destination is None:
        self.destination = geometry_msgs.msg.PoseStamped()
    else:
      self.header = std_msgs.msg.Header()
      self.box = jsk_recognition_msgs.msg.BoundingBox()
      self.handle_pose = geometry_msgs.msg.Pose()
      self.destination = geometry_msgs.msg.PoseStamped()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3I().pack(_x.box.header.seq, _x.box.header.stamp.secs, _x.box.header.stamp.nsecs))
      _x = self.box.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_10dfI7d3I().pack(_x.box.pose.position.x, _x.box.pose.position.y, _x.box.pose.position.z, _x.box.pose.orientation.x, _x.box.pose.orientation.y, _x.box.pose.orientation.z, _x.box.pose.orientation.w, _x.box.dimensions.x, _x.box.dimensions.y, _x.box.dimensions.z, _x.box.value, _x.box.label, _x.handle_pose.position.x, _x.handle_pose.position.y, _x.handle_pose.position.z, _x.handle_pose.orientation.x, _x.handle_pose.orientation.y, _x.handle_pose.orientation.z, _x.handle_pose.orientation.w, _x.destination.header.seq, _x.destination.header.stamp.secs, _x.destination.header.stamp.nsecs))
      _x = self.destination.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_7d().pack(_x.destination.pose.position.x, _x.destination.pose.position.y, _x.destination.pose.position.z, _x.destination.pose.orientation.x, _x.destination.pose.orientation.y, _x.destination.pose.orientation.z, _x.destination.pose.orientation.w))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.box is None:
        self.box = jsk_recognition_msgs.msg.BoundingBox()
      if self.handle_pose is None:
        self.handle_pose = geometry_msgs.msg.Pose()
      if self.destination is None:
        self.destination = geometry_msgs.msg.PoseStamped()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.box.header.seq, _x.box.header.stamp.secs, _x.box.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.box.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.box.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 156
      (_x.box.pose.position.x, _x.box.pose.position.y, _x.box.pose.position.z, _x.box.pose.orientation.x, _x.box.pose.orientation.y, _x.box.pose.orientation.z, _x.box.pose.orientation.w, _x.box.dimensions.x, _x.box.dimensions.y, _x.box.dimensions.z, _x.box.value, _x.box.label, _x.handle_pose.position.x, _x.handle_pose.position.y, _x.handle_pose.position.z, _x.handle_pose.orientation.x, _x.handle_pose.orientation.y, _x.handle_pose.orientation.z, _x.handle_pose.orientation.w, _x.destination.header.seq, _x.destination.header.stamp.secs, _x.destination.header.stamp.nsecs,) = _get_struct_10dfI7d3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.destination.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.destination.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 56
      (_x.destination.pose.position.x, _x.destination.pose.position.y, _x.destination.pose.position.z, _x.destination.pose.orientation.x, _x.destination.pose.orientation.y, _x.destination.pose.orientation.z, _x.destination.pose.orientation.w,) = _get_struct_7d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3I().pack(_x.box.header.seq, _x.box.header.stamp.secs, _x.box.header.stamp.nsecs))
      _x = self.box.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_10dfI7d3I().pack(_x.box.pose.position.x, _x.box.pose.position.y, _x.box.pose.position.z, _x.box.pose.orientation.x, _x.box.pose.orientation.y, _x.box.pose.orientation.z, _x.box.pose.orientation.w, _x.box.dimensions.x, _x.box.dimensions.y, _x.box.dimensions.z, _x.box.value, _x.box.label, _x.handle_pose.position.x, _x.handle_pose.position.y, _x.handle_pose.position.z, _x.handle_pose.orientation.x, _x.handle_pose.orientation.y, _x.handle_pose.orientation.z, _x.handle_pose.orientation.w, _x.destination.header.seq, _x.destination.header.stamp.secs, _x.destination.header.stamp.nsecs))
      _x = self.destination.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_7d().pack(_x.destination.pose.position.x, _x.destination.pose.position.y, _x.destination.pose.position.z, _x.destination.pose.orientation.x, _x.destination.pose.orientation.y, _x.destination.pose.orientation.z, _x.destination.pose.orientation.w))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.box is None:
        self.box = jsk_recognition_msgs.msg.BoundingBox()
      if self.handle_pose is None:
        self.handle_pose = geometry_msgs.msg.Pose()
      if self.destination is None:
        self.destination = geometry_msgs.msg.PoseStamped()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.box.header.seq, _x.box.header.stamp.secs, _x.box.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.box.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.box.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 156
      (_x.box.pose.position.x, _x.box.pose.position.y, _x.box.pose.position.z, _x.box.pose.orientation.x, _x.box.pose.orientation.y, _x.box.pose.orientation.z, _x.box.pose.orientation.w, _x.box.dimensions.x, _x.box.dimensions.y, _x.box.dimensions.z, _x.box.value, _x.box.label, _x.handle_pose.position.x, _x.handle_pose.position.y, _x.handle_pose.position.z, _x.handle_pose.orientation.x, _x.handle_pose.orientation.y, _x.handle_pose.orientation.z, _x.handle_pose.orientation.w, _x.destination.header.seq, _x.destination.header.stamp.secs, _x.destination.header.stamp.nsecs,) = _get_struct_10dfI7d3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.destination.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.destination.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 56
      (_x.destination.pose.position.x, _x.destination.pose.position.y, _x.destination.pose.position.z, _x.destination.pose.orientation.x, _x.destination.pose.orientation.y, _x.destination.pose.orientation.z, _x.destination.pose.orientation.w,) = _get_struct_7d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_10dfI7d3I = None
def _get_struct_10dfI7d3I():
    global _struct_10dfI7d3I
    if _struct_10dfI7d3I is None:
        _struct_10dfI7d3I = struct.Struct("<10dfI7d3I")
    return _struct_10dfI7d3I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_7d = None
def _get_struct_7d():
    global _struct_7d
    if _struct_7d is None:
        _struct_7d = struct.Struct("<7d")
    return _struct_7d
