; Auto-generated. Do not edit!


(cl:in-package jsk_footstep_msgs-msg)


;//! \htmlinclude ExecFootstepsResult.msg.html

(cl:defclass <ExecFootstepsResult> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass ExecFootstepsResult (<ExecFootstepsResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ExecFootstepsResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ExecFootstepsResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name jsk_footstep_msgs-msg:<ExecFootstepsResult> is deprecated: use jsk_footstep_msgs-msg:ExecFootstepsResult instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ExecFootstepsResult>) ostream)
  "Serializes a message object of type '<ExecFootstepsResult>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ExecFootstepsResult>) istream)
  "Deserializes a message object of type '<ExecFootstepsResult>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ExecFootstepsResult>)))
  "Returns string type for a message object of type '<ExecFootstepsResult>"
  "jsk_footstep_msgs/ExecFootstepsResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ExecFootstepsResult)))
  "Returns string type for a message object of type 'ExecFootstepsResult"
  "jsk_footstep_msgs/ExecFootstepsResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ExecFootstepsResult>)))
  "Returns md5sum for a message object of type '<ExecFootstepsResult>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ExecFootstepsResult)))
  "Returns md5sum for a message object of type 'ExecFootstepsResult"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ExecFootstepsResult>)))
  "Returns full string definition for message of type '<ExecFootstepsResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ExecFootstepsResult)))
  "Returns full string definition for message of type 'ExecFootstepsResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ExecFootstepsResult>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ExecFootstepsResult>))
  "Converts a ROS message object to a list"
  (cl:list 'ExecFootstepsResult
))
